### ISSUE TITLE
spinner never goes away on Firefox Android

### ISSUE THREAD

**Issue by karlcow** [GoogleChrome/chromium-dashboard#366]
Hi an issue has been opened on https://webcompat.com/issues/2901
also at https://github.com/webcompat/web-bugs/issues/2901

You need to use Firefox on Android to reproduce.

URL: https://www.chromestatus.com/feature/5671161102860288
Browser / Version: Firefox Mobile 48.0
Operating System: Android 5.1
Problem type: Mobile site is not usable

Steps to Reproduce
1) Navigate to: https://www.chromestatus.com/feature/5671161102860288
2) …

Expected Behavior:
Site content can be interact with

Actual Behavior:
Spinner overlay doesn't disappear, keeping the content e.g. links, out of reach.

The spinner is 

```html
<div id="spinner"><img src="/static/img/ring.svg"></div>
```

```css
body.loading #spinner {
	display: flex;
}


#spinner {
	display: none;
	-ms-grid-row-align: center;
	align-items: center;
	justify-content: center;
	position: fixed;
	height: calc(100% - 54px - 135px);
	max-width: 768px;
	width: 100%;
}
```

I guess it's the `.loading` which is not unset. Because as soon as we remove the first property, this is working.

probably somewhere there is an instruction to remove the loading when DOMContentReady
