### ISSUE TITLE
Css hover event changes size of image

### ISSUE THREAD

**Issue by issammani** [GoogleChrome/chromium-dashboard#766]
I am building a very simple responsive nav and I think, I found a bug in chrome.
As the GIF shows the intended behavior is, when the div (.header__mobilenav__icon), wrapping the spans, is hovered the margin-bottom shrinks from 10px to 8px. This works fine in Firexfox and the old Edge.

In chrome and the new Edge the behavior is shown in the GIF below. 

![chrome-capture](https://user-images.githubusercontent.com/26678795/75097492-9ffabe00-55ab-11ea-9a85-17e60929082d.gif)

index.html
```html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="description" content="@@meta_description">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>more blablabla</title>
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,700&display=swap" rel="stylesheet">
    <link media="screen" type="text/css" href="css/style.min.css" rel="stylesheet">
</head>

<body>
    <div class="wrapper">
        <header>
            <div class="header__logo">
                <a href="/">
                    <picture>
                        <source srcset="images/logo-small.svg" media="(max-width: 1000px)"><img src="images/logo.svg" alt="personal logo"></picture>
                </a>
            </div>
            <div class="header__mobilenav__icon hide">
                <div class="header__mobilenav__icon__wrapper"><span></span> <span></span> <span></span></div>
            </div>
            <div class="header__mobilenav__cta hide">
                <button>Hire me</button>
            </div>
            <div class="header__mobilenav__menu hide">
                <div class="nav__item"><a class="active" href="#">Home</a></div>
                <div class="nav__item"><a href="#">Work</a></div>
                <div class="nav__item"><a href="#">Lab</a></div>
                <div class="nav__item"><a href="#">About</a></div>
                <div class="nav__item"><a href="#">Contact</a></div>
            </div>
            <nav>
                <div class="nav__item"><a class="active" href="#">Home</a></div>
                <div class="nav__item"><a href="#">Work</a></div>
                <div class="nav__item"><a href="#">Lab</a></div>
                <div class="nav__item"><a href="#">About</a></div>
                <div class="nav__item"><a href="#">Contact</a></div>
            </nav>
        </header>
    </div>
</body>

</html>
```

style.min.css
```css
body,
html {
    font-family: "Poppins", sans-serif;
    height: 100%
}

*,
body,
html {
    margin: 0;
    padding: 0
}

header .header__logo a {
    width: 100%;
    height: 100%
}

header {
    display: grid;
    padding: 20px 0;
    box-sizing: border-box;
    grid-column: 2/12;
    grid-template-columns: repeat(12, 1fr);
    height: 100px
}

@media screen and (max-width:1000px) {
    header {
        grid-template-columns: 50px auto 130px;
        grid-column: 1/13;
        box-shadow: 0 2px 2px -2px rgba(0, 0, 0, .2);
        padding: 20px
    }
}

header .header__logo {
    grid-column: 1/3;
    height: 100%
}

header .header__logo a img {
    height: 100%;
    width: auto
}

@media screen and (max-width:1000px) {
    header .header__logo {
        grid-column: 2/3;
        grid-row: 1;
        justify-self: center
    }
    header .header__logo img {
        height: 50px
    }
}

header .header__mobilenav__cta {
    -webkit-box-pack: center;
    justify-content: center;
    -webkit-box-align: center;
    align-items: center;
    grid-column: 3/4;
    height: 100%
}

header .header__mobilenav__cta button {
    outline: none;
    border: none;
    border-radius: 5px;
    background-color: #2832fe;
    color: #fff;
    font-size: 17px;
    width: 130px;
    height: 45px;
    cursor: pointer;
    -webkit-transition: all .3s ease-in-out;
    transition: all .3s ease-in-out
}

header .header__mobilenav__cta button:hover {
    background-color: #161fd1
}

@media screen and (max-width:1000px) {
    header .header__mobilenav__cta {
        display: -webkit-box!important;
        display: flex!important;
        justify-self: flex-end
    }
}

header .header__mobilenav__icon {
    grid-column: 1/2;
    height: 100%;
    -webkit-box-pack: center;
    justify-content: center;
    -webkit-box-align: end;
    align-items: flex-end;
    -webkit-box-orient: vertical;
    -webkit-box-direction: normal;
    flex-direction: column;
    z-index: 3;
    -webkit-transition: all .3s ease-in-out;
    transition: all .3s ease-in-out
}

@media screen and (max-width:1000px) {
    header .header__mobilenav__icon {
        display: -webkit-box!important;
        display: flex!important;
        justify-self: flex-start
    }
}

header .header__mobilenav__icon .header__mobilenav__icon__wrapper {
    width: 50px;
    cursor: pointer;
    -webkit-transition: all .3s ease-in-out;
    transition: all .3s ease-in-out
}

header .header__mobilenav__icon .header__mobilenav__icon__wrapper:hover span:nth-child(1),
header .header__mobilenav__icon .header__mobilenav__icon__wrapper:hover span:nth-child(2) {
    background: red;
    margin-bottom: 8px
}

header .header__mobilenav__icon .header__mobilenav__icon__wrapper.is-active {
    -webkit-transition: all .3s ease-in-out;
    transition: all .3s ease-in-out;
    -webkit-transition-delay: .6s;
    transition-delay: .6s;
    -webkit-transform: rotate(45deg);
    transform: rotate(45deg)
}

header .header__mobilenav__icon .header__mobilenav__icon__wrapper.is-active span:nth-child(2) {
    width: 0
}

header .header__mobilenav__icon .header__mobilenav__icon__wrapper.is-active span:nth-child(1),
header .header__mobilenav__icon .header__mobilenav__icon__wrapper.is-active span:nth-child(3) {
    -webkit-transition-delay: .3s;
    transition-delay: .3s
}

header .header__mobilenav__icon .header__mobilenav__icon__wrapper.is-active span:nth-child(1) {
    -webkit-transform: translateY(10px);
    transform: translateY(10px)
}

header .header__mobilenav__icon .header__mobilenav__icon__wrapper.is-active span:nth-child(3) {
    -webkit-transform: translateY(-10px) rotate(90deg);
    transform: translateY(-10px) rotate(90deg)
}

header .header__mobilenav__icon .header__mobilenav__icon__wrapper span {
    border-radius: 1px;
    height: 5px;
    width: 50px;
    background: #2832fe;
    display: block;
    -webkit-transition: all .3s ease-in-out;
    transition: all .3s ease-in-out
}

header .header__mobilenav__icon .header__mobilenav__icon__wrapper span:nth-child(1),
header .header__mobilenav__icon .header__mobilenav__icon__wrapper span:nth-child(2) {
    margin-bottom: 10px
}

header .header__mobilenav__menu {
    -webkit-box-orient: vertical;
    -webkit-box-direction: normal;
    flex-direction: column;
    -webkit-box-align: center;
    align-items: center;
    position: absolute;
    background: #fff;
    z-index: 2;
    height: 100vh;
    width: 100vw;
    padding-top: 120px;
    box-sizing: border-box;
    top: 0;
    left: 0
}

@media screen and (max-width:1000px) {
    header .header__mobilenav__menu {
        display: -webkit-box;
        display: flex
    }
}

header .header__mobilenav__menu .nav__item {
    margin-bottom: 20px
}

header .header__mobilenav__menu .nav__item a {
    text-decoration: none;
    font-weight: 700;
    color: rgba(0, 0, 0, .5);
    font-size: 25px;
    -webkit-transition: all .3s ease-in-out;
    transition: all .3s ease-in-out
}

header .header__mobilenav__menu .nav__item a.active,
header .header__mobilenav__menu .nav__item a:hover,
header nav .nav__item a.active,
header nav .nav__item a:hover {
    color: #2832fe
}

header nav {
    display: grid;
    grid-column: 6/13;
    height: 100%;
    grid-template-columns: repeat(10, 1fr)
}

@media screen and (max-width:1000px) {
    header nav {
        display: none
    }
}

header nav .nav__item {
    width: 100%;
    height: 100%;
    display: -webkit-box;
    display: flex;
    -webkit-box-pack: end;
    justify-content: flex-end;
    -webkit-box-align: center;
    align-items: center
}

header nav .nav__item:nth-child(1) {
    grid-column-start: 1;
    grid-column-end: 3
}

header nav .nav__item:nth-child(2) {
    grid-column-start: 3;
    grid-column-end: 5
}

header nav .nav__item:nth-child(3) {
    grid-column-start: 5;
    grid-column-end: 7
}

header nav .nav__item:nth-child(4) {
    grid-column-start: 7;
    grid-column-end: 9
}

header nav .nav__item:nth-child(5) {
    grid-column-start: 9;
    grid-column-end: 11
}

header nav .nav__item a {
    text-decoration: none;
    color: #000;
    font-weight: 500;
    -webkit-transition: all .5s ease-in-out;
    transition: all .5s ease-in-out
}

.wrapper {
    display: grid;
    grid-template-columns: repeat(12, 1fr)
}

.hide {
    display: none!important
}
```
