### ISSUE TITLE
Research modern CSS approach and style guides

### ISSUE THREAD

**Issue by jrobbins** [GoogleChrome/chromium-dashboard#891]
I want to phase out approaches that are dated and use current best practices.

**Comment by jrobbins** [comment]
Looking through the pages at:
https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks

I see:
"In some browsers, form elements do not inherit font styling by default" and "Across browsers form elements use different box sizing rules for different widgets".  So, we need this in reset.css:
```css
button, 
input, 
select, 
textarea { 
  font-family: inherit; 
  font-size: 100%; 
  box-sizing: border-box; 
  padding: 0; margin: 0; 
} 

textarea { 
  overflow: auto; 
} 
```
